### ISSUE TITLE
Research Email Trigger Solution

### ISSUE THREAD

**Issue by JeffQuit** [JeffQuit/MERN---Project-3---Mobile-Vehicle-Detail-Application#1]
Need an email system that will trigger emails when new appointments are booked for washes

**Comment by JeffQuit** [comment]
Mailchimp looks the best
sendgrid 2nd.

**Comment by jonnikim** [comment]
MailChimp:
- https://us17.admin.mailchimp.com/account/api/
- https://mailchimp.com/developer/guides/marketing-api-quick-start/
- https://github.com/mailchimp/mailchimp-marketing-node/

**Comment by jonnikim** [comment]
Scrapped MailChimp as it didn't fit our needs.

Send Grid is a great alternative.
