### ISSUE TITLE
Set Up Insagram Feed NPM Tool via react-instafeed

### ISSUE THREAD

**Issue by JeffQuit** [JeffQuit/MERN---Project-3---Mobile-Vehicle-Detail-Application#9]

**Comment by jonnikim** [comment]
Requires Facebook Developer. Waiting on client to create one.

Using Instagram Basic Display API

Resources:
https://www.instagram.com/developer/
https://developers.facebook.com/docs/instagram-basic-display-api/getting-started
https://developers.facebook.com/

**Example:**
https://github.com/ilkeraltin/react-with-instagram-api

**Comment by jonnikim** [comment]
Hold off on Insta-Feed, may be able to use Instagram API directly.
https://instafeedjs.com/#/

**Comment by jonnikim** [comment]
Instagram requires OAUTH and refresh tokens aren't available for the way that we intend. Clients won't be able to authenticate to view client's instagram page.

Instagram retired their old API which allowed for open access to instagram calls.
